"""Predeclared trusted host oracle/graph probes; no model code or isolated qualification."""

import argparse
import hashlib
import json
import platform
from collections import Counter
from importlib.metadata import version
from pathlib import Path

import numpy as np
from task66_state_controls import probes

from graybench.circuit_wire import WireError
from graybench.datasets import PINS, load_suite
from graybench.graph_anchors import PublicAnchorRegistry
from graybench.graph_delta import DeltaGraphArena
from graybench.graph_limits import GraphLimits
from graybench.graph_rpc import validate_root_shapes
from graybench.graph_wire import GraphArena, wire_bytes
from graybench.identity import canonical, identity
from graybench.provenance import source_manifest
from graybench.task66_revision import CHECK, REQUIREMENT, revised_task

LIMITS = GraphLimits(message_bytes=16 * 1024 * 1024, depth=128)


def sha(data):
    return hashlib.sha256(data).hexdigest()


def tasks(cache):
    return tuple(load_suite(suite, cache)[66] for suite in ("normal", "hard"))


def plan(cache):
    sources = tasks(cache)
    return {
        "kind": "graybench_task66_state_plan_v1",
        "engine_source": source_manifest(),
        "dataset_pins": PINS,
        "source_tasks": [source.digest for source in sources],
        "revised_tasks": [revised_task(source).digest for source in sources],
        "public_tasks": [revised_task(source).public.digest for source in sources],
        "requirement_sha256": sha(REQUIREMENT.encode()),
        "checker_sha256": sha(CHECK.encode()),
        "scripts": {
            name: sha(Path(__file__).with_name(name).read_bytes())
            for name in ("task66_state_controls.py", "task66_state_verification.py")
        },
        "cases": [
            {
                "suite": source.public.suite,
                "id": probe.name,
                "semantic_expectation": probe.expectation,
                "rationale": probe.rationale,
                "completion_sha256": sha(probe.completion.encode()),
            }
            for source in sources
            for probe in probes(source)
        ],
        "graph_limits": LIMITS.record(),
        "graph_expectation": (
            "Measure encoding support without fallback; encoder WireError is separate "
            "from semantic correctness. Decode/protocol errors abort verification."
        ),
        "global_phase_samples": 65,
        "matrix_entry_mutants": 128,
        "recorded_graph_projection": (
            "Node-kind counts, resource-bound booleans and verdicts; "
            "autogenerated SDK names/UUIDs and raw graph bytes are not replay-bound"
        ),
    }


def authored(task, probe):
    code = (
        task.public.prompt + probe.completion if task.public.suite == "normal" else probe.completion
    )
    scope = {}
    exec(compile(code, "<trusted-authored-W-control>", "exec"), scope)
    return scope[task.public.entry_point]


def checker():
    scope = {}
    exec(compile(CHECK, "<trusted-W-check>", "exec"), scope)
    return scope


def verdict(check, implementation):
    calls = 0

    def proxy():
        nonlocal calls
        calls += 1
        return implementation()

    try:
        check(proxy)
    except AssertionError as error:
        return {"outcome": "fail", "detail": str(error), "calls": calls}
    return {"outcome": "pass", "detail": None, "calls": calls}


def graph_trial(check, implementation, anchors):
    sender = DeltaGraphArena(
        GraphArena(side="judge", session="W-host", limits=LIMITS, anchors=anchors),
        wire_limit=LIMITS.message_bytes,
    )
    receiver = DeltaGraphArena(
        GraphArena(side="candidate", session="W-host", limits=LIMITS, anchors=anchors),
        wire_limit=LIMITS.message_bytes,
    )
    request = sender.snapshot({"args": (), "kwargs": {}}, sequence=1)
    incoming = receiver.prepare(json.loads(wire_bytes(request)), sequence=1)
    validate_root_shapes(incoming.snapshot)
    roots = receiver.commit(incoming)
    value = implementation(*roots["args"], **roots["kwargs"])
    try:
        response = receiver.snapshot({**roots, "result": value, "exception_args": None}, sequence=1)
    except WireError as error:
        return {"support": "unsupported", "detail": str(error), "oracle": None}
    prepared = sender.prepare(json.loads(wire_bytes(response)), sequence=1)
    validate_root_shapes(prepared.snapshot, response=True, raised=None)
    node_kinds = dict(sorted(Counter(row["kind"] for row in prepared.snapshot["nodes"]).items()))
    result = sender.commit(prepared)["result"]
    return {
        "support": "supported",
        "detail": None,
        "oracle": verdict(check, lambda: result),
        "node_kinds": node_kinds,
        "request_within_wire_limit": len(wire_bytes(request)) <= LIMITS.message_bytes,
        "response_within_wire_limit": len(wire_bytes(response)) <= LIMITS.message_bytes,
        "expanded_snapshot_within_state_limit": len(wire_bytes(prepared.snapshot))
        <= LIMITS.message_bytes,
    }


def build(cache, declared):
    if canonical(declared) != canonical(plan(cache)):
        raise ValueError("Current sources differ from the predeclared W plan")
    scope = checker()
    check = scope["check"]
    anchors = PublicAnchorRegistry.capture()
    rows = []
    for source in tasks(cache):
        task = revised_task(source)
        for probe in probes(source):
            # Separate fresh instances: host checks may populate SDK caches.
            graph = graph_trial(check, authored(task, probe), anchors)
            host = verdict(check, authored(task, probe))
            if host["outcome"] != probe.expectation or host["calls"] != 1:
                raise ValueError(f"Host control disagrees: {source.public.suite}/{probe.name}")
            if graph["support"] == "supported" and graph["oracle"] != host:
                raise ValueError(f"Graph control differs: {source.public.suite}/{probe.name}")
            rows.append(
                {
                    "suite": source.public.suite,
                    "id": probe.name,
                    "expectation": probe.expectation,
                    "host": host,
                    "graph": graph,
                }
            )
    vector = np.zeros(8, dtype=complex)
    vector[[1, 2, 4]] = 1 / np.sqrt(3)
    density = np.outer(vector, vector.conj())
    phases = []
    for angle in np.linspace(-np.pi, np.pi, 65):
        actual = np.exp(1j * angle) * vector
        scope["assert_w_density"](np.outer(actual, actual.conj()))
        phases.append(float(angle))
    mutants = 0
    for row in range(8):
        for column in range(8):
            for offset in (1e-6, 1e-6j):
                changed = density.copy()
                changed[row, column] += offset
                try:
                    scope["assert_w_density"](changed)
                except AssertionError:
                    mutants += 1
                else:
                    raise ValueError("Density entry mutant survived")
    return {
        "kind": "graybench_task66_state_host_verification_v1",
        "plan_digest": identity(declared),
        "engine_source_digest": source_manifest()["digest"],
        "environment": {
            "python": platform.python_version(),
            "packages": {name: version(name) for name in ("qiskit", "numpy", "scipy")},
        },
        "controls": rows,
        "host_outcomes": dict(Counter(row["host"]["outcome"] for row in rows)),
        "graph_support": dict(Counter(row["graph"]["support"] for row in rows)),
        "graph_outcomes": dict(
            Counter(
                row["graph"]["oracle"]["outcome"]
                for row in rows
                if row["graph"]["support"] == "supported"
            )
        ),
        "density_oracle_global_phase_samples": phases,
        "density_oracle_entry_mutants_rejected": mutants,
        "runtime_qualified": False,
        "candidate_encoder_integrity_qualified": False,
        "independent_human_admission": False,
        "release_eligible": False,
        "model_generations": 0,
        "limitations": [
            (
                "Same-process trusted authored host probes, not isolated exec"
                "ution or arbitrary model code"
            ),
            (
                "Graph replay binds the declared projection; raw envelopes an"
                "d autogenerated SDK identities are not retained"
            ),
            "SDK evolution/graph codecs still need independent qualification",
            (
                "65 state-vector phase and 128 entry probes calibrate oracle "
                "arithmetic, not full-circuit semantic mutations"
            ),
            "Unsupported correct constructions remain blockers; no fallback or exclusion",
            (
                "No sampler, Docker or API calls; no sampling execution or na"
                "tive provenance is attested"
            ),
        ],
    }


def verify(report, declared, cache):
    if canonical(report) != canonical(build(cache, declared)):
        raise ValueError("Saved W evidence differs from exact projected recreation")
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("cache", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    plan_path = args.output.with_name("host-plan.json")
    if args.check:
        declared = json.loads(plan_path.read_bytes())
        report = json.loads(args.output.read_bytes())
        verify(report, declared, args.cache)
    else:
        declared = plan(args.cache)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with plan_path.open("x", encoding="utf-8", newline="\n") as stream:
            stream.write(json.dumps(declared, indent=2, sort_keys=True) + "\n")
        report = build(args.cache, declared)
        with args.output.open("x", encoding="utf-8", newline="\n") as stream:
            stream.write(json.dumps(report, indent=2, sort_keys=True) + "\n")
    print(
        json.dumps(
            {
                key: report[key]
                for key in ("host_outcomes", "graph_support", "graph_outcomes", "release_eligible")
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
